updated windows build

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -208,11 +208,11 @@ jobs:
           architecture: x64
 
               
-      - name: Debug Find OpenSSL DLLs
-        shell: msys2 {0}
-        run: |
-          find /mingw64/bin -iname "*ssl*.dll"
-          find /mingw64/bin -iname "*crypto*.dll"
+      # - name: Debug Find OpenSSL DLLs
+      #   shell: msys2 {0}
+      #   run: |
+      #     find /mingw64/bin -iname "*ssl*.dll"
+      #     find /mingw64/bin -iname "*crypto*.dll"
 
       - name: Add Windows Python to PATH
         shell: msys2 {0}
@@ -230,28 +230,28 @@ jobs:
         env:
           pythonLocation: ${{ env.pythonLocation }}
 
-      - name: Check that required DLLs are in PATH
-        shell: msys2 {0}
-        run: |
-          export PATH="$(cygpath -u "$pythonLocation"):/mingw64/bin:$PATH"
-          pkg-config --libs --static libcrypto
-          echo "🔎 Checking for required DLLs in PATH:"
-          for dll in libssl-3-x64.dll libcrypto-3-x64.dll python311.dll; do
-            found=0
-            for dir in $(echo $PATH | tr ':' '\n'); do
-              if [ -f "$dir/$dll" ]; then
-                echo "✅ Found $dll in $dir"
-                found=1
-                break
-              fi
-            done
-            if [ "$found" -eq 0 ]; then
-              echo "❌ Missing $dll!"
-              exit 1
-            fi
-          done
-        env:
-          pythonLocation: ${{ env.pythonLocation }}
+      # - name: Check that required DLLs are in PATH
+      #   shell: msys2 {0}
+      #   run: |
+      #     export PATH="$(cygpath -u "$pythonLocation"):/mingw64/bin:$PATH"
+      #     pkg-config --libs --static libcrypto
+      #     echo "🔎 Checking for required DLLs in PATH:"
+      #     for dll in libssl-3-x64.dll libcrypto-3-x64.dll python311.dll; do
+      #       found=0
+      #       for dir in $(echo $PATH | tr ':' '\n'); do
+      #         if [ -f "$dir/$dll" ]; then
+      #           echo "✅ Found $dll in $dir"
+      #           found=1
+      #           break
+      #         fi
+      #       done
+      #       if [ "$found" -eq 0 ]; then
+      #         echo "❌ Missing $dll!"
+      #         exit 1
+      #       fi
+      #     done
+      #   env:
+      #     pythonLocation: ${{ env.pythonLocation }}
           
       - name: Build pymgclient Wheel
         shell: msys2 {0}
@@ -269,16 +269,16 @@ jobs:
         env:
           pythonLocation: ${{ env.pythonLocation }}
     
-      - name: Check mgclient.pyd DLL Dependencies (MSYS2)
-        run: |
-          mgclient_path=$(find $pythonLocation -name "mgclient.cp*.pyd" | head -n1)
-          if [ -z "$mgclient_path" ]; then
-            echo "mgclient.pyd not found!"
-            exit 1
-          fi
-          echo "Found: $mgclient_path"
-          objdump -p "$mgclient_path" | grep 'DLL Name'
-        shell: msys2 {0}
+      # - name: Check mgclient.pyd DLL Dependencies (MSYS2)
+      #   run: |
+      #     mgclient_path=$(find $pythonLocation -name "mgclient.cp*.pyd" | head -n1)
+      #     if [ -z "$mgclient_path" ]; then
+      #       echo "mgclient.pyd not found!"
+      #       exit 1
+      #     fi
+      #     echo "Found: $mgclient_path"
+      #     objdump -p "$mgclient_path" | grep 'DLL Name'
+      #   shell: msys2 {0}
 
 
       
